const cfg=window.SIMIMEDI_CONFIG, db=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);let recipes=[],editing=null;const token=new URLSearchParams(location.search).get('edit')||'';const canEdit=!!token;
const $=id=>document.getElementById(id);$('add').hidden=!canEdit;
function draw(){let q=$('search').value.toLowerCase();let rows=recipes.filter(r=>JSON.stringify(r.data).toLowerCase().includes(q));$('grid').innerHTML=rows.map(r=>`<article class="card" data-id="${r.id}"><div class="emoji">${r.data.emoji||'🥘'}</div><h3>${r.data.title||'Untitled recipe'}</h3><p class="tags">${(r.data.tags||[]).join(' · ')}</p><span class="muted">${r.data.meal||''} ${r.data.time?'· '+r.data.time:''}</span></article>`).join('')||'<p class="muted">No recipes yet.</p>';document.querySelectorAll('.card').forEach(x=>x.onclick=()=>openRecipe(x.dataset.id))}
async function load(){let {data:libs}=await db.from('libraries').select('id').eq('slug',cfg.librarySlug);if(!libs?.length){$('status').textContent='The database is connected. Your cookbook needs its one-time setup.';if(canEdit)$('setup').showModal();return}let {data,error}=await db.from('recipes').select('*').eq('library_id',libs[0].id).order('updated_at',{ascending:false});if(error){$('status').textContent='Could not load recipes: '+error.message;return}recipes=data||[];$('status').textContent=canEdit?'Editing mode · keep this link private':'Viewing mode';draw()}
$('create').onclick=async()=>{let secret=crypto.randomUUID()+crypto.randomUUID();let {error}=await db.rpc('create_library',{p_name:'SimiMedi Cooking',p_slug:cfg.librarySlug,p_edit_token:secret});if(error){alert(error.message);return}let url=location.origin+location.pathname+'?edit='+encodeURIComponent(secret);await navigator.clipboard.writeText(url);alert('Your secret editing link was copied. Save it somewhere private.');location.href=url};
$('search').oninput=draw;$('add').onclick=()=>{$('importer').showModal()};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.mode))});
function parseRecipeText(raw,source=''){let lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),title=lines[0]||'Imported recipe',ing=[],steps=[],section='';for(let line of lines.slice(1)){let low=line.toLowerCase();if(/^(ingredients|ingredientes|suroviny|ingredience)[: ]*$/.test(low)){section='ing';continue}if(/^(instructions|method|directions|preparation|preparación|postup|příprava)[: ]*$/.test(low)){section='steps';continue}let quantity=/^(?:[-•*]\s*)?(?:\d+[\d\s.,/½¼¾⅓⅔–-]*|½|¼|¾)\s*(?:g|kg|ml|l|tsp|tbsp|cup|cups|lžičk|lžíc|cucharad|cuchar)?\b/i.test(line);let numbered=/^\d+[.)]\s+/.test(line);if(section==='ing'||(!section&&quantity))ing.push(line.replace(/^[-•*]\s*/,''));else if(section==='steps'||numbered)steps.push(line.replace(/^\d+[.)]\s*/,''))}if(!ing.length&&lines.length>1)ing=lines.slice(1,Math.min(lines.length,7));return{title,meal:'Dinner',time:'',ingredients:ing,steps,tags:[],emoji:'🥘',source}}
function openImported(data){$('importer').close();editing={id:null,data};$('title').value=data.title||'';$('meal').value=data.meal||'Dinner';$('time').value=data.time||'';$('ingredients').value=(data.ingredients||[]).join('\n');$('steps').value=(data.steps||[]).join('\n');$('tags').value=(data.tags||[]).join(', ');$('remove').hidden=true;$('editor').showModal()}
$('manual').onclick=()=>openImported({title:'',meal:'Dinner',time:'',ingredients:[],steps:[],tags:[],emoji:'🥘'});
$('importText').onclick=()=>{let text=$('rawText').value.trim();if(!text)return alert('Please paste the recipe text first.');openImported(parseRecipeText(text))};
$('imageFile').onchange=async e=>{let file=e.target.files[0];if(!file)return;$('ocrProgress').textContent='Reading the image…';try{let result=await Tesseract.recognize(file,'eng+spa+ces',{logger:m=>{if(m.progress)$('ocrProgress').textContent=`Reading image… ${Math.round(m.progress*100)}%`}});$('ocrProgress').textContent='';openImported(parseRecipeText(result.data.text))}catch(err){$('ocrProgress').textContent='Could not read this image. Try a clearer screenshot or paste the text.'}};
$('importLink').onclick=async()=>{let url=$('sourceUrl').value.trim();if(!url)return alert('Please paste a link first.');$('importLink').disabled=true;$('importLink').textContent='Checking link…';try{let res=await fetch(url);if(!res.ok)throw new Error('blocked');let html=await res.text(),doc=new DOMParser().parseFromString(html,'text/html'),scripts=[...doc.querySelectorAll('script[type="application/ld+json"]')];let recipe=null;for(let s of scripts){try{let j=JSON.parse(s.textContent),items=Array.isArray(j)?j:(j['@graph']||[j]);recipe=items.find(x=>x['@type']==='Recipe'||(Array.isArray(x['@type'])&&x['@type'].includes('Recipe')));if(recipe)break}catch{}}if(!recipe)throw new Error('no recipe data');let steps=Array.isArray(recipe.recipeInstructions)?recipe.recipeInstructions.map(x=>typeof x==='string'?x:(x.text||'')).filter(Boolean):[recipe.recipeInstructions].filter(Boolean);openImported({title:recipe.name||'Imported recipe',meal:recipe.recipeCategory||'Dinner',time:recipe.totalTime||recipe.cookTime||'',ingredients:recipe.recipeIngredient||[],steps,tags:(recipe.keywords||'').split(',').map(x=>x.trim()).filter(Boolean),emoji:'🥘',source:url})}catch{alert('This website blocked automatic reading or did not expose recipe data. Please use the Text or Screenshot option instead.')}finally{$('importLink').disabled=false;$('importLink').textContent='Extract recipe'}};
function openRecipe(id){let r=recipes.find(x=>x.id===id);if(!canEdit&&r){alert(`${r.data.title}\n\nIngredients:\n${(r.data.ingredients||[]).join('\n')}\n\nMethod:\n${(r.data.steps||[]).join('\n')}`);return}editing=r||null;$('title').value=r?.data.title||'';$('meal').value=r?.data.meal||'Dinner';$('time').value=r?.data.time||'';$('ingredients').value=(r?.data.ingredients||[]).join('\n');$('steps').value=(r?.data.steps||[]).join('\n');$('tags').value=(r?.data.tags||[]).join(', ');$('remove').hidden=!r;$('editor').showModal()}
$('save').onclick=async()=>{let data={title:$('title').value.trim(),meal:$('meal').value,time:$('time').value.trim(),ingredients:$('ingredients').value.split('\n').map(x=>x.trim()).filter(Boolean),steps:$('steps').value.split('\n').map(x=>x.trim()).filter(Boolean),tags:$('tags').value.split(',').map(x=>x.trim()).filter(Boolean),emoji:'🥘',source:editing?.data?.source||''};let {error}=await db.rpc('save_recipe',{p_slug:cfg.librarySlug,p_edit_token:token,p_id:editing?.id||null,p_data:data});if(error){alert(error.message);return}$('editor').close();await load()};
$('remove').onclick=async()=>{if(!confirm('Delete this recipe?'))return;let {error}=await db.rpc('delete_recipe',{p_slug:cfg.librarySlug,p_edit_token:token,p_id:editing.id});if(error){alert(error.message);return}$('editor').close();await load()};load();
